// serve.mjs -- minimal HTTPS static file server for the staged _site tree.
//
// WebCrypto + WebAuthn require a secure origin.  We serve over HTTPS with a
// self-signed cert for wklm.online (generated by global-setup); Chromium maps
// wklm.online -> 127.0.0.1 and ignores the cert error, so the page origin is
// https://wklm.online and the WebAuthn RP id (`wklm.online`) matches.
//
// Correct Content-Type for .mjs (ES module) and .wasm (streaming compile) is
// essential: a wrong type makes the `<script type=module>` import or the
// WebAssembly instantiation fail.  COOP/COEP are set so SharedArrayBuffer /
// any cross-origin isolation Emscripten may want is available (harmless here).
import { createReadStream, existsSync, statSync, readFileSync } from 'node:fs';
import { createServer } from 'node:https';
import { extname, join, normalize } from 'node:path';

const root = process.env.SITE_DIR;
const certFile = process.env.CERT_FILE;
const keyFile = process.env.KEY_FILE;
const port = Number(process.env.PORT || 8443);

if (!root || !existsSync(root)) {
  console.error(`serve.mjs: SITE_DIR not found: ${root}`);
  process.exit(1);
}
if (!certFile || !keyFile || !existsSync(certFile) || !existsSync(keyFile)) {
  console.error('serve.mjs: CERT_FILE/KEY_FILE not found');
  process.exit(1);
}

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.wasm': 'application/wasm',
  '.json': 'application/json; charset=utf-8',
  '.eml': 'text/plain; charset=utf-8',
  '.ml': 'text/plain; charset=utf-8',
};

const server = createServer(
  { cert: readFileSync(certFile), key: readFileSync(keyFile) },
  (req, res) => {
    try {
      let urlPath = decodeURIComponent((req.url || '/').split('?')[0]);
      if (urlPath.endsWith('/')) urlPath += 'index.html';
      // Resolve and contain within root (no path traversal).
      const resolved = normalize(join(root, urlPath));
      if (!resolved.startsWith(normalize(root))) {
        res.writeHead(403);
        res.end('forbidden');
        return;
      }
      let filePath = resolved;
      if (existsSync(filePath) && statSync(filePath).isDirectory()) {
        filePath = join(filePath, 'index.html');
      }
      if (!existsSync(filePath) || !statSync(filePath).isFile()) {
        res.writeHead(404);
        res.end('not found');
        return;
      }
      const type = TYPES[extname(filePath)] || 'application/octet-stream';
      res.writeHead(200, {
        'Content-Type': type,
        'Cross-Origin-Opener-Policy': 'same-origin',
        'Cross-Origin-Embedder-Policy': 'require-corp',
        'Cache-Control': 'no-store',
      });
      createReadStream(filePath).pipe(res);
    } catch (e) {
      res.writeHead(500);
      res.end(String(e));
    }
  },
);

server.listen(port, '127.0.0.1', () => {
  // Playwright's webServer waits on this readiness line / the port being up.
  console.log(`serve.mjs: https://127.0.0.1:${port} serving ${root}`);
});
