name: Build LaTeX Blog with Dynamic Index

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'index_template.tex'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-base texlive-latex-extra texlive-fonts-recommended pandoc git  # Ensure git is installed

    - name: Generate Dynamic Content for Index
      run: |
        cp index_template.tex index.tex
        echo "\\section*{Articles}" >> index.tex
        for file in posts/*.tex; do
          title=$(basename "$file" .tex)
          date=$(git log -1 --format="%ad" --date=short -- "$file")
          echo "\\subsection*{\\href{./$(basename "$file" .tex).html}{$title}}" >> index.tex
          echo "\\textit{Published on: $date}" >> index.tex
        done
        echo "\\end{document}" >> index.tex

    - name: Compile LaTeX Document
      run: |
        pdflatex index.tex  # Assuming pdflatex is used; adjust if using another LaTeX compiler like XeLaTeX or LuaTeX

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
