name: Build LaTeX Blog

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'styles/**'  # Ensure changes in styles also trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache LaTeX and Pandoc
      uses: actions/cache@v2
      with:
        path: |
          /usr/share/texlive
          /usr/share/pandoc
        key: ${{ runner.os }}-texlive-pandoc-${{ hashFiles('**/*.tex') }}

    - name: Install TeX Live and Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-base texlive-latex-extra texlive-fonts-recommended pandoc

    - name: Convert LaTeX to HTML
      run: |
        mkdir -p _site
        mkdir -p _site/styles
        cp styles/bernoulli-bauhaus.css _site/styles/
        for file in posts/*.tex; do
          echo "Processing $file"
          pandoc "$file" --pdf-engine=xelatex -s -o "_site/$(basename ${file%.tex}.html)"
          echo "<link rel='stylesheet' href='/styles/bernoulli-bauhaus.css'>" | cat - "_site/$(basename ${file%.tex}.html)" > temp && mv temp "_site/$(basename ${file%.tex}.html)"
          if [ $? -ne 0 ]; then
            echo "Error processing $file"
            exit 1
          fi
          echo "Generated HTML for $(basename ${file%.tex}.html)"
        done

    - name: Generate Index Page
      run: |
        echo "<html><head><title>Blog Index</title><link rel='stylesheet' href='/styles/bernoulli-bauhaus.css'></head><body><h1>Blog Posts</h1><ul>" > _site/index.html
        for file in _site/*.html; do
          if [ $(basename "$file") != "index.html" ]; then
            title=$(basename "$file" .html)
            echo "<li><a href='/${title}.html'>$title</a></li>" >> _site/index.html
          fi
        done
        echo "</ul></body></html>" >> _site/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
