name: Build LaTeX Blog with MathJax

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'styles/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-base texlive-latex-extra texlive-fonts-recommended pandoc

    - name: Convert LaTeX to HTML
      run: |
        mkdir -p output
        for file in posts/*.tex; do
          pandoc $file --to=html5 --standalone --mathjax --output=output/$(basename "${file%.tex}.html")
          # Adjust the HTML to include the MathJax script and remove any local script references
          sed -i '1s|^|<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"><link rel="stylesheet" href="styles/bernoulli-bauhaus.css"><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js"></script>|' output/$(basename "${file%.tex}.html")
          echo '</head><body>' | cat - output/$(basename "${file%.tex}.html") > temp.html && mv temp.html output/$(basename "${file%.tex}.html")
        done

    - name: Generate Index Page
      run: |
        echo "<html><head><title>Blog Index</title><link rel='stylesheet' href='/styles/bernoulli-bauhaus.css'></head><body><h1>Blog Posts</h1><ul>" > index.html
        for file in *.html; do
          if [ $(basename "$file") != "index.html" ]; then
            title=$(basename "$file" .html)
            echo "<li><a href='/${title}.html'>$title</a></li>" >> index.html
          fi
        done
        echo "</ul></body></html>" >> index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output