name: Build LaTeX Blog

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'styles/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-base texlive-latex-extra texlive-fonts-recommended pandoc
        npm install katex

    - name: Convert LaTeX to HTML
      run: |
        mkdir -p output
        for file in posts/*.tex; do
          pandoc $file --to=html5 --standalone --mathjax --output=output/$(basename "${file%.tex}.html")
          # Modify the HTML to include correct headers, links to KaTeX, and CSS
          sed -i '1s|^|<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css" integrity="sha384-wcIxkf4k558AjM3Yz3BBFQUbk/zgIYC2R0QpeeYb+TwlBVMrlgLqwRjRtGZiK7ww" crossorigin="anonymous"><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js" integrity="sha384-hIoBPJpTUs74ddyc4bFZSM1TVlQDA60VBbJS0oA934VSz82sBx1X7kSx2ATBDIyd" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>|' output/$(basename "${file%.tex}.html")
          echo "<link rel='stylesheet' href='styles/bernoulli-bauhaus.css'></head><body>" | cat - output/$(basename "${file%.tex}.html") > temp.html && mv temp.html output/$(basename "${file%.tex}.html")
          # Remove local MathJax script and fix any other structural issues
          sed -i '/<script src="\/usr\/share\/javascript\/mathjax/d' output/$(basename "${file%.tex}.html")
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
