name: Build LaTeX Blog

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'styles/**'  # Ensure changes in styles also trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache LaTeX and Pandoc
      uses: actions/cache@v2
      with:
        path: |
          /usr/share/texlive
          /usr/share/pandoc
        key: ${{ runner.os }}-texlive-pandoc-${{ hashFiles('**/*.tex') }}

    - name: Install TeX Live, Pandoc, and KaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-base texlive-latex-extra texlive-fonts-recommended pandoc
        npm install katex

    - name: Convert LaTeX to HTML
      run: |
        mkdir -p _site
        mkdir -p _site/styles
        cp styles/bernoulli-bauhaus.css _site/styles/
        for file in posts/*.tex; do
          echo "Processing $file"
          pandoc "$file" --mathjax --pdf-engine=xelatex -s -o "_site/$(basename ${file%.tex}.html)"
          echo "<link rel='stylesheet' href='/styles/bernoulli-bauhaus.css'>" | cat - "_site/$(basename ${file%.tex}.html)" > temp && mv temp "_site/$(basename ${file%.tex}.html)"
          if [ $? -ne 0 ]; then
            echo "Error processing $file"
            exit 1
          fi
          echo "Generated HTML for $(basename ${file%.tex}.html)"
        done

    - name: Add KaTeX to HTML
      run: |
        # Inject KaTeX scripts and styles into each HTML file
        for file in _site/*.html; do
          sed -i '1s|^|<head><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css" integrity="sha384-wcIxkf4k558AjM3Yz3BBFQUbk/zgIYC2R0QpeeYb+TwlBVMrlgLqwRjRtGZiK7ww" crossorigin="anonymous"><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js" integrity="sha384-hIoBPJpTUs74ddyc4bFZSM1TVlQDA60VBbJS0oA934VSz82sBx1X7kSx2ATBDIyd" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script></head>|' "$file"
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
